version: "3.8"

services:
  backend:
    build: ./
    command: ["sh", "./scripts/startup.sh"]
    ports:
      - "8080:8080"
    env_file:
      - config.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      - config.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data/

volumes:
  postgresdata:
    driver: local